### ISSUE TITLE
Include quiz files in the clean-up process

### ISSUE THREAD

**Issue by robertjank** [wheleph/nttt#76]
Some of the newly created projects support quizzes. For example, [Catch the bus](https://projects.raspberrypi.org/en/projects/catch-the-bus) has a step called [Reflection](https://projects.raspberrypi.org/en/projects/catch-the-bus/7), which presents a quiz with 3 questions.

The Catch the bus project in GitHub contains an extra folder (called `quiz1`), which contains 3 markdown files: `question_1.md`, `question_2.md` and `question_3.md`. These markdown files should be cleaned up by NTTT similar to the step markdown files.

The way to find out whether there are quizzes in a project and how many question files there are in a project is to parse the contents of the `meta.yml` file. The following is a fragment of the `meta.yml` of Catch the bus:
```
title: Catch the bus
(some entries not shown)
steps:
  - title: Introduction
  (some steps not shown)
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  (remaining steps not shown)
```
The `knowledge_quiz` entry indicates that a step is actually a quiz.
The `path` entry defines the name of the folder containing the question files of the quiz (here `quiz1`).
The `questions` entry defines the number of question files in the `quiz1` folder (here 3).
